version: "3"

services:

  locust-master:
    image: locustio/locust
    container_name:
      locust-master
    env_file: master-env.env
    ports:
      - "8089:8089"
    # environment:
    #   - LOCUST_MODE=master
    #   - LOCUSTFILE_PATH="/locust/locustfile.py"
    #   - TARGET_URL="http://localhost:80"
    volumes:
      - ./tests:/locust
    entrypoint:
      - locust
      - -f
      - /locust/locustfile.py
      - -H
      - http://localhost:80
      - --master

  locust-slave:
    image: locustio/locust
    container_name:
      locust-slave
    env_file: slave-env.env
    # environment:
    #   - LOCUST_MODE=slave
    #   - LOCUST_MASTER_HOST=locust-master
    #   - LOCUST_MASTER_PORT=5557
    volumes:
      - ./tests:/locust
    depends_on:
      - locust-master
    entrypoint:
      - locust
      - -f
      - /locust/locustfile.py
      - --slave
